#网站
#标题
title: littlestarsx's blog
#副标题
subtitle:
#描述
description: littlestarsx个人博客
#作者
author: littlestarsx
#语言
language: zh-Hans
#时区
timezone: Asia/Shanghai

#网址
#网址
url: littlestarsx.github.io
#网站根目录
root: /
#文章的 永久链接 格式 默认值：:year/:month/:day/:title/
permalink: :year/:month/:day/:title/
#永久链接中各部分的默认值
#permalink_defaults:

#目录
#资源文件夹，这个文件夹用来存放内容。默认值：source
source_dir: source
#公共文件夹，这个文件夹用于存放生成的站点文件。默认值：public
public_dir: public
#标签文件夹 默认值：tags
tag_dir: tags
#归档文件夹 默认值：archives
archive_dir: archives
#分类文件夹 默认值：categories
category_dir: categories
#Include code文件夹 默认值：downloads/code
code_dir: downloads/code
#国际化（i18n）文件夹	默认值：lang
i18n_dir: lang
#跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。
#skip_render:

#文章
#新文章的文件名称 默认值：:title.md
new_post_name: :title.md
#预设布局	post
default_layout: post
#在中文和英文之间加入空格 默认值：false
auto_spacing: false
#把标题转换为 title case 默认值：false
titlecase: false
#在新标签中打开链接 默认值：true
external_link: true
#把文件名称转换为 把文件名称转换为 (1) 小写或 (2) 大写 默认值：0
filename_case: 1
#显示草稿	false
render_drafts: false
#启动Asset文件夹 默认值：false
post_asset_folder: false
#把链接改为与根目录的相对位址 默认值：false
relative_link: false
#显示未来的文章 默认值：true
future: true
#代码块的设置
#highlight:

#分类 & 标签
#默认分类 默认值：uncategorized
#default_category:
#分类别名
#category_map:
#标签别名
#tag_map:

#日期/时间格式
#日期格式 默认值：YYYY-MM-DD
date_format	: YYYY-MM-DD
#时间格式 默认值H:mm:ss
time_format	: HH:mm:ss

#分页
#每页显示的文章量 (0 = 关闭分页功能) 默认值：10
per_page: 10
#分页目录 默认值：page
pagination_dir: page

#扩展
#当前主题名称。值为false时禁用主题
theme: next
#部署部分的设置
deploy:
  type: git
  repo: git@github.com:littlestarsx/littlestarsx.github.io.git
  branch: master
  #message: [message]
  name: littlestarsx
  email: loveshao1113@126.com
  #extend_dirs: [extend directory]